### ISSUE TITLE
你的效果比 dribbble 上的要好~

### ISSUE THREAD

**Issue by Hitomis** [xmuSistone/android-page-transition#1]
在 dribbble 上看到的一个特别想去实现的设计，准备国庆来了，开始写。结果。。。结果。。让我哭会儿~

**Comment by xmuSistone** [comment]
其实，在早先已经有一个仓库了，实现的效果是一毛一样的。我也是撸完了这一份代码才发觉的。别人的那一份仓库地址是：https://github.com/qs-lll/ExpandingPager 
只是，他的那一份代码，比较卡，交互没设计好，屏幕适配也问题百出。所以还是推荐直接参考我的这一份代码，如果有问题，我能随时帮改~
