### ISSUE TITLE
add picture manually

### ISSUE THREAD

**Issue by HamidReza-katani** [xmuSistone/android-page-transition#11]
Hi
is it possible to add pictures to viewPager manually? I want to add pictures that I get from the website (using volley) to it. can it be done?

**Comment by HamidReza-katani** [comment]
I also used an url instead of an image on the assets folder but it didn't work

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, this is ViewPager's work. Try FragmentStateAdapter,  and make it loop.

**Comment by xmuSistone** [comment]
Mostly, it's ViewPager's work. Please try FragmentStateAdapter, and make it loop.

**Comment by xmuSistone** [comment]
Mostly, it's ViewPager's work. Please try FragmentStateAdapter, and make it loop.

**Comment by xmuSistone** [comment]
Mostly, it's ViewPager's work. Try FragmentStateAdapter and make it loop.
