### ISSUE TITLE
Can the background color be an expanded version of the image in the card?

### ISSUE THREAD

**Issue by anitaa1990** [xmuSistone/android-page-transition#6]
Hi, 

Thanks for the great library. I just had a small request/doubt on whether the following is possible.
I would like to change the background of the page to reflect the image that is currently at the centre. 

Please find attached screenshot for clarity.
![screen shot 2017-04-07 at 6 50 18 pm](https://cloud.githubusercontent.com/assets/22608780/24801746/172f0696-1bc3-11e7-91f6-fe6d6fd72009.png)

Can you please guide me on how to achieve this with this library?

**Comment by xmuSistone** [comment]
I m sorry that it is hard to realize your reflect effects. But there still exists some other ways you may want to try.
Once the fragment is created, you are able to get the position rect of  the center-ImageView-card. And you can extract the partial bitmap for the area of that rect from the big background bitmap.
