### ISSUE TITLE
Is there an option to expand/collapse the draglayout by calling a method manually?

### ISSUE THREAD

**Issue by anitaa1990** [xmuSistone/android-page-transition#7]
Hi,

I would like to be able to expand the draglayout without any click function. Please let me know if this is possible at the moment and if so, how would I go about doing that?

Thanks for the awesome library!! You rock!

**Comment by xmuSistone** [comment]
Yeah, it is easy to expand the draglayout. Wrap the onClick function into a new public method, hope that helps.

**Comment by anitaa1990** [comment]
Hi, I checked it out and had a doubt. How do we collapse the draglayout? In the clickListener there is an option to expand the draglayout and then open the detail screen. No option to collapse the layout.

Could you please guide on how to do this?

**Comment by xmuSistone** [comment]
add a new method as follows:
```java
public void collapse() {
      if (mDragHelper.smoothSlideViewTo(topView, originX, originY)) {
                ViewCompat.postInvalidateOnAnimation(DragLayout.this);
      }
}
```

**Comment by iman2420** [comment]
`dragLayout.performClick();`  not work!
how to expand manually?
