### ISSUE TITLE
viewpager

### ISSUE THREAD

**Issue by cxlm** [xmuSistone/android-page-transition#8]
How to adjust the location of the viewPage is not centered on the top of the slide, as if not the left cycle sliding

**Comment by xmuSistone** [comment]
in initial case, the single card is in the center position.
in expancd case, the whole view is in the center position. 
If u need some other customization, please modify the [DragLayout ](https://github.com/xmuSistone/android-page-transition/blob/master/android-page-transition/app/src/main/java/com/stone/transition/DragLayout.java) by yourself.
